# Generated by Django 3.1.2 on 2021-12-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='sex',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
