# Generated by Django 3.1.2 on 2021-12-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211211_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='interest_rate',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='status',
            name='overdraft_limit_quarterly',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='status',
            name='overdrate_interest_rate',
            field=models.FloatField(default=0.15),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='sex',
            field=models.CharField(default=None, help_text='M: Male or F: Female', max_length=1),
        ),
    ]
