# Generated by Django 3.1.2 on 2021-12-11 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211211_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='branches',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the Branch', max_length=150)),
                ('address', models.CharField(help_text='The address of the Branch', max_length=150)),
                ('phone_num', models.CharField(help_text='HongKong Phone number', max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.RemoveField(
            model_name='status',
            name='overdrate_interest_rate',
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='job_title',
            field=models.CharField(help_text='employee/manager', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='max_loan_auth',
            field=models.DecimalField(decimal_places=2, help_text='The maximum loan authority of the employee', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='overdraft_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=3),
        ),
        migrations.AlterField(
            model_name='status',
            name='account_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=3),
        ),
        migrations.CreateModel(
            name='loans',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.05, max_digits=3)),
                ('date_issue', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(default=datetime.datetime(2022, 6, 9, 12, 57, 28, 187477, tzinfo=utc))),
                ('loan_type', models.CharField(choices=[('Car', 'car loan'), ('Hou', 'house loan'), ('Oth', 'Other loan')], default=None, max_length=3)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.branches')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.basicdetails')),
            ],
        ),
    ]
